In [1]:
import pandas as pd
import numpy as np

In [2]:
path =r"C:\Users\jyanes\Desktop\JUAN\ACAMICA\GALICIA\CONTENT_CATEGORY.csv"
path1 =r"C:\Users\jyanes\Desktop\JUAN\ACAMICA\GALICIA\CONTENT_CATEGORY_BOTTOM.csv"
path2 =r"C:\Users\jyanes\Desktop\JUAN\ACAMICA\GALICIA\CONTENT_CATEGORY_TOP.csv"
path3 =r"C:\Users\jyanes\Desktop\JUAN\ACAMICA\GALICIA\conversiones.csv"
path4 =r"C:\Users\jyanes\Desktop\JUAN\ACAMICA\GALICIA\device_data.csv"
path5 =r"C:\Users\jyanes\Desktop\JUAN\ACAMICA\GALICIA\PAGE.csv"
path6 =r"C:\Users\jyanes\Desktop\JUAN\ACAMICA\GALICIA\pageviews.csv"
path8 =r"C:\Users\jyanes\Desktop\JUAN\ACAMICA\GALICIA\sampleSubmission.csv"
path9 =r"C:\Users\jyanes\Desktop\JUAN\ACAMICA\GALICIA\SITE_ID.csv"

In [7]:
df_test = pd.read_csv(path6,parse_dates=['FEC_EVENT'],nrows=50000)
df_test.drop(['CONTENT_CATEGORY','CONTENT_CATEGORY_TOP','CONTENT_CATEGORY_BOTTOM','SITE_ID','ON_SITE_SEARCH_TERM'],axis=1,inplace=True)

In [9]:
df_test['mes'] = df_test['FEC_EVENT'].apply(lambda x: x.month)

In [17]:
user = df_test.groupby('PAGE')

In [43]:
for x,y in user:
    print(x)
    print(y['USER_ID'].value_counts())

1
24    424
22    180
50    138
0     107
58     86
12     84
1      78
32     57
13     50
15     49
44     41
7      39
29     36
62     36
42     34
49     34
48     31
28     29
10     25
4      25
11     21
61     18
55     16
2      16
51     15
56     15
53     11
63     10
31      9
14      7
52      6
40      5
30      3
57      3
34      3
26      2
9       2
60      2
16      1
36      1
38      1
41      1
54      1
Name: USER_ID, dtype: int64
2
24    289
35    193
47    179
32    176
50    145
61    143
5     133
36    129
22    125
0     125
4     123
38    108
30    104
12    104
20    102
62    101
58     96
26     90
41     87
37     85
15     78
44     76
1      75
40     74
31     71
42     71
53     69
60     67
2      66
56     66
     ...
9      49
11     49
8      48
16     48
46     47
45     46
51     45
13     43
23     42
3      40
7      40
25     38
43     35
33     35
19     33
28     31
55     30
34     29
48     22
29     19
21     18
59     15
14     14
6      13
39     11
52     10
54      7
18      5
63      4
10      2
Name: USER_ID, Length: 64, dtype: int64
3
30    161
36    134
4      94
62     93
38     88
20     85
40     70
55     57
45     53
34     52
60     50
9      46
16     46
0      44
43     43
35     41
50     40
31     39
61     35
15     34
25     34
44     32
2      32
5      32
33     29
57     29
17     28
46     28
59     24
21     24
32     21
24     21
12     19
51     18
49     17
1      17
47     15
42     13
6      13
48     11
56     11
8      10
53      9
3       8
22      7
19      7
37      7
7       6
27      4
58      4
13      4
14      3
11      2
23      2
41      2
26      2
39      2
18      2
10      1
Name: USER_ID, dtype: int64
4
20    20
34    16
36    16
0     15
47    15
9     13
35    13
32    13
62    12
33    12
31    11
45    10
44    10
59    10
49    10
1      9
2      9
15     9
42     8
40     8
16     8
46     7
60     7
12     7
25     6
57     6
55     6
17     5
61     4
53     4
19     4
5      3
6      3
8      3
22     3
21     3
43     3
48     2
50     2
26     2
30     2
38     1
41     1
11     1
18     1
23     1
7      1
24     1
3      1
51     1
37     1
Name: USER_ID, dtype: int64
5
62    39
30    32
4     24
45    21
40    19
31    19
61    11
17    11
38    10
25    10
20     9
55     9
2      9
60     8
43     8
53     7
36     7
46     6
50     6
34     6
33     6
9      5
16     5
12     5
35     4
47     4
5      4
22     3
6      2
8      2
0      2
56     2
59     2
14     1
15     1
19     1
39     1
44     1
49     1
3      1
1      1
32     1
Name: USER_ID, dtype: int64
6
36    34
30    29
4     27
35    16
0     12
5      5
60     5
50     4
45     4
48     3
16     3
17     3
20     3
31     3
24     2
61     2
34     2
43     2
32     2
40     1
42     1
12     1
57     1
1      1
Name: USER_ID, dtype: int64
7
35    1
36    1
0     1
Name: USER_ID, dtype: int64
8
7     1
38    1
21    1
4     1
36    1
0     1
Name: USER_ID, dtype: int64
9
53    1090
24     142
32     102
36      88
38      83
0       78
47      75
50      72
22      66
42      57
58      55
26      53
12      51
7       51
31      50
49      30
56      30
1       29
11      28
28      21
62      20
61      20
8       20
60      19
29      19
2       19
40      14
34      10
52      10
13       9
44       6
48       6
57       6
59       6
9        4
33       3
6        3
4        3
37       2
41       2
14       2
18       1
51       1
10       1
63       1
Name: USER_ID, dtype: int64
10
24    816
36    786
22    439
32    436
58    403
4     347
53    336
0     327
50    316
41    308
61    296
44    249
26    239
38    238
56    228
60    199
34    181
7     170
12    157
13    143
1     110
42    106
31    103
9      96
49     94
8      79
28     71
29     66
11     66
48     63
2      61
15     56
14     56
54     51
62     44
40     44
33     38
10     37
51     33
52     22
59     19
23     18
57     15
6      14
47     12
63     11
18      1
Name: USER_ID, dtype: int64
11
0     300
49     94
Name: USER_ID, dtype: int64
12
36    775
0     324
53    281
61    243
42    106
49     94
1      78
28     71
10     37
52     22
32     18
6      14
7       6
57      3
26      1
18      1
Name: USER_ID, dtype: int64
13
58    75
0     71
50    59
36    52
1     37
51    23
52     4
2      1
Name: USER_ID, dtype: int64
14
16    1405
53     512
35     173
47     155
24     149
0      125
37     124
61     124
41     122
60     121
36     119
5      119
42     101
17      92
3       92
34      80
32      71
44      65
22      62
58      60
50      59
27      58
13      53
9       49
28      49
23      49
38      48
46      44
31      40
15      39
20      39
26      38
49      38
57      37
1       35
40      30
56      30
12      29
45      28
25      27
19      27
54      26
11      25
48      24
8       21
51      21
33      20
14      19
2       16
43      14
7       13
6       13
62      12
39       9
21       9
52       8
10       7
29       7
4        2
63       2
Name: USER_ID, dtype: int64
15
24    233
36    174
0     137
32    117
22    111
61    103
58     90
50     89
12     87
53     78
38     74
41     72
26     70
56     55
28     52
34     49
7      47
44     43
29     41
1      39
9      37
49     36
13     32
60     31
48     28
8      28
15     27
14     23
62     18
42     16
10     16
31     16
51     15
33     14
2      13
11     11
4      10
47      9
52      9
57      5
40      5
54      5
23      5
59      3
6       3
18      1
Name: USER_ID, dtype: int64
16
22    28
53    22
38    16
26    16
24     9
44     7
41     7
15     5
0      4
51     2
32     2
Name: USER_ID, dtype: int64
17
38    9
47    7
53    5
0     4
7     4
42    3
2     3
40    3
32    3
50    2
52    2
29    2
12    2
58    2
62    2
34    1
61    1
31    1
28    1
22    1
13    1
8     1
56    1
4     1
1     1
Name: USER_ID, dtype: int64
18
36    775
53    282
1      78
29     50
10     37
0      24
32     18
7       6
6       5
26      1
18      1
Name: USER_ID, dtype: int64
19
35    6
29    3
38    3
0     3
36    2
41    2
27    2
5     2
1     2
34    1
31    1
50    1
26    1
22    1
21    1
4     1
58    1
Name: USER_ID, dtype: int64
20
0     28
36    28
35    26
34    24
16    21
62    21
5     19
45    15
30    14
60    13
32    12
25    12
2     11
59    11
33    11
1     11
31    10
20     9
49     8
46     8
9      8
47     8
61     8
24     8
22     6
40     6
38     6
44     6
57     6
15     6
12     5
43     5
17     5
4      4
37     4
8      3
26     3
13     2
18     2
42     2
48     2
50     2
19     1
21     1
56     1
Name: USER_ID, dtype: int64
21
5     41
62    31
20    31
35    27
38    23
17    21
55    19
24    19
16    17
60    16
2     14
45    13
0     13
31    12
30    11
36    11
43    11
33    11
12    10
51    10
32     9
9      8
34     8
61     8
1      8
8      8
59     7
40     6
57     5
50     4
19     4
27     3
46     3
49     2
3      2
56     2
44     1
18     1
47     1
42     1
22     1
Name: USER_ID, dtype: int64
22
24    146
36     86
26     68
58     46
56     38
41     33
13     22
4      16
14     11
60      9
0       8
15      8
32      8
11      8
44      8
22      6
54      6
48      5
50      5
34      4
2       4
9       3
29      3
53      3
7       3
51      2
8       2
63      1
10      1
23      1
40      1
52      1
59      1
31      1
Name: USER_ID, dtype: int64
23
4     33
36    20
60    14
30    11
34     9
9      8
53     6
15     5
31     5
38     5
43     5
20     5
44     4
21     4
14     4
37     4
16     4
46     3
59     3
55     3
13     2
58     2
0      2
25     2
26     2
45     2
50     2
39     1
47     1
49     1
8      1
57     1
Name: USER_ID, dtype: int64
24
59    17
5     17
55    11
34     6
33     6
0      5
12     5
31     4
57     4
40     4
20     3
30     2
6      2
16     2
37     2
60     2
49     2
27     1
25     1
36     1
17     1
15     1
51     1
10     1
35     1
61     1
Name: USER_ID, dtype: int64
25
59    5
57    4
0     4
31    3
33    3
49    2
55    1
12    1
40    1
34    1
Name: USER_ID, dtype: int64
26
33    26
5     23
59    22
17    21
55    20
31    18
40    15
34    14
60    13
12    13
43    11
0     10
6     10
57    10
20     8
35     8
51     8
16     7
25     6
1      6
36     5
21     5
61     4
45     4
27     3
49     3
2      3
30     2
47     2
4      2
3      2
32     2
24     1
38     1
39     1
44     1
15     1
10     1
50     1
Name: USER_ID, dtype: int64
27
36    129
4      64
30     38
34     23
35     20
43     19
60     19
20     18
25     17
57     16
37     15
46     15
38     13
16     11
2      11
31     10
55      8
13      7
24      7
0       7
12      6
53      5
40      5
49      5
47      5
59      5
33      4
8       4
50      4
26      4
5       4
15      3
62      3
44      3
32      3
14      2
17      2
23      2
9       2
61      2
58      2
7       1
48      1
3       1
Name: USER_ID, dtype: int64
28
0    1
Name: USER_ID, dtype: int64
29
22    2
53    2
49    2
0     1
Name: USER_ID, dtype: int64
30
0    1
Name: USER_ID, dtype: int64
31
21    4
30    3
49    2
38    1
16    1
36    1
3     1
0     1
Name: USER_ID, dtype: int64
32
55    10
33    10
31     8
5      6
20     5
62     4
57     4
35     4
61     3
9      3
12     3
16     3
0      3
17     2
50     2
51     2
59     2
8      2
1      2
32     2
36     1
22     1
49     1
18     1
60     1
Name: USER_ID, dtype: int64
33
47    4
44    4
5     2
34    2
0     2
31    1
59    1
57    1
56    1
Name: USER_ID, dtype: int64
34
48    2
7     1
13    1
2     1
1     1
0     1
Name: USER_ID, dtype: int64
35
0    1
Name: USER_ID, dtype: int64
36
53    17
26    11
24     7
44     5
22     4
15     4
0      3
51     2
41     2
Name: USER_ID, dtype: int64
37
53    15
26    11
44     5
24     5
22     4
15     4
0      3
51     2
41     2
Name: USER_ID, dtype: int64
38
53    14
26    11
44     5
22     4
15     4
24     3
0      3
51     2
41     2
Name: USER_ID, dtype: int64
39
25    30
38    20
60    15
36    11
43     9
51     8
50     8
24     8
35     7
30     6
9      6
44     5
42     5
22     4
32     4
15     3
0      3
26     2
45     2
5      2
31     1
34     1
40     1
56     1
59     1
3      1
62     1
Name: USER_ID, dtype: int64
40
35    243
32    165
5     118
27     97
41     96
50     85
26     78
56     78
37     74
39     70
20     67
44     57
61     55
22     54
19     48
45     48
2      48
31     45
3      45
58     44
8      38
40     37
49     34
38     33
12     30
51     28
16     26
23     25
46     23
24     19
13     17
42     17
57     16
9      16
14     12
17     12
34     11
25     10
36     10
21      7
4       7
53      7
30      7
47      6
33      5
48      4
28      4
60      3
6       3
29      3
55      3
7       3
0       2
10      2
54      2
11      2
15      1
63      1
Name: USER_ID, dtype: int64
41
30    129
40     19
36     17
4       8
35      5
44      4
60      3
31      3
24      2
5       2
47      1
43      1
33      1
32      1
22      1
0       1
Name: USER_ID, dtype: int64
42
30    15
36     9
35     9
56     7
40     7
34     6
60     5
4      5
24     4
2      3
20     3
0      3
43     3
25     2
17     2
16     2
13     2
50     2
32     1
33     1
59     1
21     1
47     1
15     1
14     1
3      1
57     1
26     1
Name: USER_ID, dtype: int64
43
30    64
45    22
4     18
38    14
43    12
24     6
44     4
21     4
35     2
5      2
0      2
57     1
1      1
Name: USER_ID, dtype: int64
44
47    18
28    10
13     8
25     7
0      6
17     5
23     5
42     5
61     5
40     4
31     4
53     3
20     3
35     3
48     2
3      2
37     2
34     2
5      2
51     2
8      2
9      2
57     2
6      1
58     1
45     1
22     1
54     1
24     1
43     1
26     1
27     1
60     1
39     1
32     1
Name: USER_ID, dtype: int64
45
47    74
11    39
20    38
57    22
38    21
26    14
17    13
32    12
33     7
25     7
24     6
22     6
43     6
61     6
37     4
46     4
4      3
13     2
0      2
34     2
41     2
45     2
54     2
42     1
44     1
12     1
9      1
7      1
1      1
30     1
Name: USER_ID, dtype: int64
46
0    1
Name: USER_ID, dtype: int64
47
4     105
36    103
60     22
44     16
53     13
22     11
41     10
54      9
32      7
61      4
7       3
62      2
49      2
56      2
58      2
0       2
51      1
11      1
10      1
9       1
8       1
2       1
Name: USER_ID, dtype: int64
48
59    12
5      9
33     9
40     6
6      5
31     5
16     4
55     4
12     4
20     4
34     3
60     2
2      2
25     2
17     2
43     2
51     2
15     1
27     1
4      1
57     1
0      1
Name: USER_ID, dtype: int64
49
59    4
57    4
33    3
31    2
49    2
55    1
12    1
40    1
34    1
0     1
Name: USER_ID, dtype: int64
50
59    4
57    4
33    3
49    2
31    1
55    1
12    1
40    1
34    1
0     1
Name: USER_ID, dtype: int64
51
0     2
45    1
Name: USER_ID, dtype: int64
52
0    1
Name: USER_ID, dtype: int64
53
0    1
Name: USER_ID, dtype: int64
54
0    1
Name: USER_ID, dtype: int64
55
30    11
36    10
38     8
35     5
17     3
4      2
50     1
48     1
47     1
43     1
32     1
31     1
20     1
15     1
12     1
0      1
Name: USER_ID, dtype: int64
56
44    3
47    2
31    1
59    1
5     1
34    1
0     1
Name: USER_ID, dtype: int64

57
30    117
36     15
4      14
5       8
62      5
46      5
44      4
20      4
59      3
42      3
17      3
32      2
16      2
19      2
33      2
35      2
40      2
55      2
60      1
31      1
25      1
37      1
38      1
50      1
9       1
57      1
2       1
0       1
Name: USER_ID, dtype: int64
58
20    12
62     8
17     7
5      6
16     5
43     4
60     4
59     3
51     3
36     3
31     3
2      2
12     2
0      2
19     2
32     2
34     1
8      1
40     1
55     1
1      1
27     1
Name: USER_ID, dtype: int64
59
20    11
17     6
5      5
62     4
43     4
59     3
51     3
36     3
16     3
60     3
19     2
2      2
31     2
32     2
0      2
34     1
12     1
8      1
40     1
55     1
Name: USER_ID, dtype: int64
60
20    8
17    6
62    4
59    3
51    3
43    3
16    3
36    3
2     2
19    2
0     2
60    2
31    1
34    1
40    1
12    1
8     1
55    1
32    1
Name: USER_ID, dtype: int64
61
33    11
36     9
20     6
12     5
55     5
62     5
51     5
34     4
31     4
2      4
40     3
9      3
6      3
35     2
1      2
27     1
43     1
18     1
17     1
8      1
5      1
0      1
Name: USER_ID, dtype: int64
62
26    12
56    11
17     2
13     2
2      2
Name: USER_ID, dtype: int64
63
47    4
29    1
12    1
11    1
61    1
50    1
24    1
7     1
38    1
2     1
Name: USER_ID, dtype: int64
64
36    20
20    12
30     8
2      7
34     5
46     4
9      4
55     4
31     3
43     2
48     2
4      2
40     1
38     1
37     1
44     1
23     1
16     1
13     1
Name: USER_ID, dtype: int64
65
36    32
20    13
25    11
30     7
4      7
46     6
21     6
9      5
31     5
55     4
12     4
16     4
43     4
40     4
37     4
57     4
34     4
60     4
2      3
59     2
24     2
44     2
15     2
14     2
13     2
32     1
26     1
38     1
39     1
49     1
50     1
53     1
7      1
56     1
33     1
Name: USER_ID, dtype: int64
66
2     2
14    1
36    1
27    1
30    1
Name: USER_ID, dtype: int64
67
41    19
2     13
56     8
50     7
26     3
21     3
63     2
49     2
53     1
51     1
48     1
30     1
29     1
27     1
25     1
15     1
Name: USER_ID, dtype: int64
68
41    15
13    10
56     8
2      6
61     5
22     4
50     4
27     3
26     3
44     2
15     2
10     1
21     1
63     1
29     1
33     1
49     1
53     1
32     1
Name: USER_ID, dtype: int64
69
30    15
4     13
36     8
20     7
2      4
46     4
38     3
34     3
8      3
37     2
13     2
9      2
55     2
31     1
49     1
43     1
14     1
12     1
Name: USER_ID, dtype: int64
70
2     2
52    1
Name: USER_ID, dtype: int64
71
47    2
5     2
38    1
2     1
17    1
49    1
Name: USER_ID, dtype: int64
72
13    11
56     7
50     6
41     5
2      5
61     4
29     3
15     2
63     1
62     1
49     1
22     1
Name: USER_ID, dtype: int64
73
41    4
2     3
4     1
Name: USER_ID, dtype: int64
74
43    2
60    2
53    2
58    2
13    2
42    1
2     1
5     1
6     1
41    1
31    1
28    1
49    1
52    1
23    1
57    1
45    1
32    1
Name: USER_ID, dtype: int64
75
2    1
Name: USER_ID, dtype: int64
76
27    3
53    2
2     2
56    1
Name: USER_ID, dtype: int64
77
15    2
2     2
4     1
Name: USER_ID, dtype: int64
78
2     1
53    1
Name: USER_ID, dtype: int64
79
56    1
2     1
25    1
48    1
Name: USER_ID, dtype: int64
80
20    5
5     5
55    4
8     2
35    2
2     2
31    1
30    1
34    1
62    1
17    1
16    1
12    1
9     1
32    1
Name: USER_ID, dtype: int64
81
59    8
33    6
20    6
6     4
55    3
12    3
40    3
16    3
2     2
34    2
43    2
51    2
31    1
17    1
15    1
4     1
27    1
Name: USER_ID, dtype: int64
82
59    12
33     9
20     6
31     5
12     4
40     4
55     3
6      3
34     3
16     3
60     2
2      2
43     2
51     2
17     1
25     1
15     1
4      1
27     1
Name: USER_ID, dtype: int64
83
57    3
4     2
42    1
5     1
2     1
Name: USER_ID, dtype: int64
84
2    1
Name: USER_ID, dtype: int64
85
35    332
47    301
37    211
5     166
46    158
27    148
3      90
23     72
25     70
30     67
16     62
19     59
17     59
57     54
42     53
44     43
20     42
45     41
6      33
43     28
21     28
4      11
39     11
61     10
33      4
49      4
12      2
34      1
31      1
Name: USER_ID, dtype: int64
86
42    9
24    3
35    3
49    1
44    1
11    1
38    1
3     1
Name: USER_ID, dtype: int64
87
35    173
47    103
5      55
27     45
3      43
17     30
46     28
57     26
19     26
37     22
25     19
23     18
61     14
6      13
21     12
16     12
44     10
45     10
42      9
20      9
33      3
39      3
49      2
30      2
43      1
12      1
Name: USER_ID, dtype: int64
88
47    54
35    19
27    14
3      9
46     7
37     6
5      6
57     2
43     2
30     2
21     2
45     1
44     1
34     1
23     1
19     1
Name: USER_ID, dtype: int64
89
30    18
35    12
23     8
19     5
4      5
3      4
44     3
61     2
45     2
27     2
57     1
47     1
46     1
42     1
16     1
Name: USER_ID, dtype: int64
90
30    9
23    8
19    3
44    3
61    1
20    1
42    1
4     1
3     1
35    1
Name: USER_ID, dtype: int64
91
20    1
30    1
4     1
3     1
42    1
35    1
Name: USER_ID, dtype: int64
92
17    2
4     1
Name: USER_ID, dtype: int64
93
4     2
57    1
Name: USER_ID, dtype: int64
94
4    1
Name: USER_ID, dtype: int64
95
4    1
Name: USER_ID, dtype: int64
96
4    1
Name: USER_ID, dtype: int64
97
4    1
Name: USER_ID, dtype: int64
98
4    1
Name: USER_ID, dtype: int64
99
36    9
4     6
32    6
15    5
30    4
61    4
43    2
33    2
37    1
35    1
57    1
44    1
50    1
25    1
17    1
55    1
6     1
34    1
Name: USER_ID, dtype: int64
100
4     3
30    1
Name: USER_ID, dtype: int64
101
4     5
36    4
Name: USER_ID, dtype: int64
102
36    14
4      6
Name: USER_ID, dtype: int64
103
36    104
4      96
60     19
44     14
53      6
22      3
58      1
51      1
24      1
Name: USER_ID, dtype: int64
104
36    59
4      9
60     2
44     2
51     1
24     1
Name: USER_ID, dtype: int64
105
16    62
42    48
6     33
57    19
4     10
Name: USER_ID, dtype: int64
106
42    48
6     33
23    14
4      9
Name: USER_ID, dtype: int64
107
36    28
60    17
4     16
44    11
53     3
Name: USER_ID, dtype: int64
108
30    24
36     5
4      5
31     3
35     2
Name: USER_ID, dtype: int64
109
30    30
36     5
4      5
31     4
35     2
Name: USER_ID, dtype: int64
110
30    63
40     8
36     6
4      5
31     4
35     2
Name: USER_ID, dtype: int64
111
44    24
4     15
32    10
36     8
22     8
40     2
59     1
54     1
Name: USER_ID, dtype: int64
112
4     4
54    1
Name: USER_ID, dtype: int64
113
35    6
36    5
4     5
57    4
30    4
60    2
59    2
26    2
50    1
46    1
43    1
40    1
24    1
13    1
Name: USER_ID, dtype: int64
114
4     4
30    1
56    1
55    1
46    1
34    1
Name: USER_ID, dtype: int64
115
4     2
35    2
17    1
Name: USER_ID, dtype: int64
116
45    1
4     1
Name: USER_ID, dtype: int64
117
4    1
Name: USER_ID, dtype: int64
118
4    2
Name: USER_ID, dtype: int64
119
4    1
Name: USER_ID, dtype: int64
120
34    3
4     1
36    1
Name: USER_ID, dtype: int64
121
4     8
28    1
Name: USER_ID, dtype: int64
122
4    8
Name: USER_ID, dtype: int64
123
44    22
36     2
40     2
59     1
4      1
32     1
Name: USER_ID, dtype: int64
124
4    1
Name: USER_ID, dtype: int64
125
46    1
4     1
Name: USER_ID, dtype: int64
126
4     2
40    1
Name: USER_ID, dtype: int64
127
4     3
36    2
40    1
Name: USER_ID, dtype: int64
128
4    1
Name: USER_ID, dtype: int64
129
36    5
35    2
4     1
Name: USER_ID, dtype: int64
130
4    1
Name: USER_ID, dtype: int64
131
4     3
36    3
57    1
Name: USER_ID, dtype: int64
132
33    3
6     2
17    2
60    1
57    1
40    1
4     1
Name: USER_ID, dtype: int64
133
59    12
30     7
61     3
60     3
16     2
4      2
Name: USER_ID, dtype: int64
134
4    1
Name: USER_ID, dtype: int64
135
28    3
4     1
Name: USER_ID, dtype: int64
136
4    1
Name: USER_ID, dtype: int64
137
4     2
49    1
Name: USER_ID, dtype: int64
138
30    2
4     1
44    1
32    1
Name: USER_ID, dtype: int64
139
23    1
45    1
4     1
33    1
40    1
Name: USER_ID, dtype: int64
140
36    9
30    6
4     6
59    4
57    2
44    2
25    2
20    2
15    2
31    1
21    1
16    1
8     1
Name: USER_ID, dtype: int64
141
30    3
4     2
Name: USER_ID, dtype: int64
142
4    1
Name: USER_ID, dtype: int64
143
58    5
4     2
14    1
24    1
Name: USER_ID, dtype: int64
144
4    1
Name: USER_ID, dtype: int64
145
4    1
Name: USER_ID, dtype: int64
146
59    4
25    2
20    2
15    2
4     2
31    1
30    1
57    1
16    1
36    1
8     1
Name: USER_ID, dtype: int64
147
54    1
4     1
Name: USER_ID, dtype: int64
148
54    1
4     1
Name: USER_ID, dtype: int64
149
54    1
4     1
Name: USER_ID, dtype: int64
150
4     2
57    1
Name: USER_ID, dtype: int64
151
4     3
57    1
Name: USER_ID, dtype: int64
152
36    1
17    1
4     1
Name: USER_ID, dtype: int64
153
36    12
16     4
34     4
20     2
57     1
53     1
50     1
5      1
4      1
Name: USER_ID, dtype: int64
154
36    8
4     5
Name: USER_ID, dtype: int64
155
30    7
4     1
Name: USER_ID, dtype: int64
156
35    3
4     2
Name: USER_ID, dtype: int64
157
35    1
4     1
Name: USER_ID, dtype: int64
158
35    1
4     1
Name: USER_ID, dtype: int64
159
4    1
Name: USER_ID, dtype: int64
160
20    6
5     5
55    4
16    1
12    1
8     1
32    1
Name: USER_ID, dtype: int64
161
5     4
12    3
55    2
40    2
6     2
61    1
27    1
25    1
37    1
15    1
10    1
34    1
33    1
Name: USER_ID, dtype: int64
162
12    2
5     1
Name: USER_ID, dtype: int64
163
25    7
5     6
15    2
38    2
26    1
24    1
51    1
Name: USER_ID, dtype: int64
164
25    4
5     3
15    2
26    1
24    1
38    1
51    1
Name: USER_ID, dtype: int64
165
25    3
15    2
5     1
51    1
26    1
Name: USER_ID, dtype: int64
166
36    9
35    5
60    2
24    2
20    2
30    1
21    1
16    1
43    1
42    1
5     1
34    1
Name: USER_ID, dtype: int64
167
5    1
Name: USER_ID, dtype: int64
168
53    3695
16     662
6       48
42      43
60      33
31       9
21       8
34       3
61       3
12       3
5        2
50       1
17       1
Name: USER_ID, dtype: int64
169
35    18
5      5
25     3
23     3
45     2
47     1
44     1
Name: USER_ID, dtype: int64
170
25    3
45    2
5     2
44    1
23    1
35    1
Name: USER_ID, dtype: int64
171
25    3
5     3
45    2
44    1
23    1
35    1
Name: USER_ID, dtype: int64
172
25    3
45    2
5     2
44    1
35    1
Name: USER_ID, dtype: int64
173
47    2
31    1
5     1
44    1
59    1
34    1
Name: USER_ID, dtype: int64
174
35    14
5      6
23     4
25     2
Name: USER_ID, dtype: int64
175

35    4
5     3
55    2
51    2
25    1
8     1
17    1
49    1
Name: USER_ID, dtype: int64
176
5     4
35    3
51    2
49    2
25    1
55    1
Name: USER_ID, dtype: int64
177
5     4
51    2
49    2
55    1
35    1
Name: USER_ID, dtype: int64
178
5     3
51    2
55    1
49    1
Name: USER_ID, dtype: int64
179
5     3
51    2
55    1
49    1
Name: USER_ID, dtype: int64
180
5     2
60    2
20    1
12    1
34    1
16    1
Name: USER_ID, dtype: int64
181
6    3
Name: USER_ID, dtype: int64
182
59    9
33    9
31    4
20    4
12    4
55    3
34    3
6     3
51    2
43    2
40    2
60    1
27    1
25    1
16    1
15    1
Name: USER_ID, dtype: int64
183
12    3
40    2
55    2
6     2
15    1
27    1
10    1
25    1
34    1
Name: USER_ID, dtype: int64
184
7    1
Name: USER_ID, dtype: int64
185
42    13
53     4
56     2
60     2
24     2
49     1
7      1
36     1
Name: USER_ID, dtype: int64
186
15    2
59    2
20    2
30    1
31    1
25    1
8     1
57    1
16    1
Name: USER_ID, dtype: int64
187
15    2
59    2
20    2
30    1
31    1
25    1
8     1
57    1
16    1
Name: USER_ID, dtype: int64
188
8    2
Name: USER_ID, dtype: int64
189
61    1
8     1
Name: USER_ID, dtype: int64
190
25    14
38     5
30     4
44     3
15     2
60     1
51     1
43     1
42     1
36     1
26     1
24     1
9      1
Name: USER_ID, dtype: int64
191
51    2
9     1
60    1
Name: USER_ID, dtype: int64
192
36    13
54     3
50     3
9      2
Name: USER_ID, dtype: int64
193
36    13
54     3
50     3
9      2
Name: USER_ID, dtype: int64
194
36    13
50     3
9      2
Name: USER_ID, dtype: int64
195
32    75
42    38
50    32
60     6
63     2
9      2
38     1
22     1
Name: USER_ID, dtype: int64
196
32    61
42    14
50    12
60     2
9      1
Name: USER_ID, dtype: int64
197
10    1
Name: USER_ID, dtype: int64
198
10    1
Name: USER_ID, dtype: int64
199
30    2
21    2
12    1
11    1
36    1
49    1
Name: USER_ID, dtype: int64
200
47    3
37    1
28    1
11    1
53    1
61    1
Name: USER_ID, dtype: int64
201
12    38
Name: USER_ID, dtype: int64
202
20    118
32     91
39     72
12     50
45     38
33     24
19     10
63      8
52      4
22      1
Name: USER_ID, dtype: int64
203
12    40
45    27
39    21
19    13
33     8
40     2
60     1
Name: USER_ID, dtype: int64
204
12    2
20    1
Name: USER_ID, dtype: int64
205
22    4
13    2
Name: USER_ID, dtype: int64
206
50    2
13    2
Name: USER_ID, dtype: int64
207
13    1
36    1
Name: USER_ID, dtype: int64
208
13    1
Name: USER_ID, dtype: int64
209
22    13
26     4
24     3
53     3
41     3
51     2
15     2
38     1
Name: USER_ID, dtype: int64
210
25    3
15    2
51    1
26    1
Name: USER_ID, dtype: int64
211
25    3
15    2
51    1
26    1
Name: USER_ID, dtype: int64
212
25    3
15    2
51    1
26    1
Name: USER_ID, dtype: int64
213
15    1
59    1
Name: USER_ID, dtype: int64
214
16    3
Name: USER_ID, dtype: int64
215
16    2
20    1
59    1
Name: USER_ID, dtype: int64
216
16    1
Name: USER_ID, dtype: int64
217
16    4
Name: USER_ID, dtype: int64
218
16    4
Name: USER_ID, dtype: int64
219
16    2
Name: USER_ID, dtype: int64
220
30    1
35    1
25    1
16    1
Name: USER_ID, dtype: int64
221
16    1
Name: USER_ID, dtype: int64
222
16    1
Name: USER_ID, dtype: int64
223
16    1
Name: USER_ID, dtype: int64
224
16    1
Name: USER_ID, dtype: int64
225
16    1
Name: USER_ID, dtype: int64
226
16    3
Name: USER_ID, dtype: int64
227
16    3
Name: USER_ID, dtype: int64
228
16    3
Name: USER_ID, dtype: int64
229
56    1
16    1
Name: USER_ID, dtype: int64
230
17    1
Name: USER_ID, dtype: int64
231
17    1
Name: USER_ID, dtype: int64
232
38    3
30    1
36    1
17    1
Name: USER_ID, dtype: int64
233
17    6
Name: USER_ID, dtype: int64
234
17    2
Name: USER_ID, dtype: int64
235
36    7
57    3
30    2
60    2
55    1
17    1
Name: USER_ID, dtype: int64
236
55    2
17    1
Name: USER_ID, dtype: int64
237
55    2
17    1
Name: USER_ID, dtype: int64
238
17    1
Name: USER_ID, dtype: int64
239
27    2
17    1
36    1
Name: USER_ID, dtype: int64
240
17    1
Name: USER_ID, dtype: int64
241
19    1
Name: USER_ID, dtype: int64
242
23    5
44    2
61    1
19    1
Name: USER_ID, dtype: int64
243
20    53
Name: USER_ID, dtype: int64
244
20    1
Name: USER_ID, dtype: int64
245
20    1
Name: USER_ID, dtype: int64
246
20    1
Name: USER_ID, dtype: int64
247
20    1
Name: USER_ID, dtype: int64
248
20    1
Name: USER_ID, dtype: int64
249
22    1
20    1
Name: USER_ID, dtype: int64
250
21    3
63    1
Name: USER_ID, dtype: int64
251
22    1
Name: USER_ID, dtype: int64
252
22    1
30    1
Name: USER_ID, dtype: int64
253
24    3
22    2
47    1
53    1
Name: USER_ID, dtype: int64
254
22    1
44    1
Name: USER_ID, dtype: int64
255
23    1
Name: USER_ID, dtype: int64
256
45    2
40    2
23    1
33    1
Name: USER_ID, dtype: int64
257
36    1
24    1
Name: USER_ID, dtype: int64
258
36    1
24    1
Name: USER_ID, dtype: int64
259
35    3
37    2
30    1
25    1
Name: USER_ID, dtype: int64
260
25    1
Name: USER_ID, dtype: int64
261
25    1
Name: USER_ID, dtype: int64
262
25    2
Name: USER_ID, dtype: int64
263
25    1
Name: USER_ID, dtype: int64
264
25    1
Name: USER_ID, dtype: int64
265
35    3
25    1
Name: USER_ID, dtype: int64
266
25    1
Name: USER_ID, dtype: int64
267
25    1
Name: USER_ID, dtype: int64
268
51    2
26    1
Name: USER_ID, dtype: int64
269
26    5
41    1
Name: USER_ID, dtype: int64
270
26    1
Name: USER_ID, dtype: int64
271
26    1
56    1
Name: USER_ID, dtype: int64
272
35    99
27    52
45    24
Name: USER_ID, dtype: int64
273
27    1
Name: USER_ID, dtype: int64
274
42    19
27     4
Name: USER_ID, dtype: int64
275
42    32
27     6
Name: USER_ID, dtype: int64
276
30    3
36    2
43    1
50    1
Name: USER_ID, dtype: int64
277
30    2
43    1
Name: USER_ID, dtype: int64
278
30    2
Name: USER_ID, dtype: int64
279
30    2
Name: USER_ID, dtype: int64
280
30    2
Name: USER_ID, dtype: int64
281
30    1
Name: USER_ID, dtype: int64
282
30    2
Name: USER_ID, dtype: int64
283
30    2
Name: USER_ID, dtype: int64
284
30    1
Name: USER_ID, dtype: int64
285
30    31
40     3
Name: USER_ID, dtype: int64
286
30    21
40     1
Name: USER_ID, dtype: int64
287
30    17
40     1
Name: USER_ID, dtype: int64
288
30    1
Name: USER_ID, dtype: int64
289
30    9
44    1
55    1
36    1
Name: USER_ID, dtype: int64
290
30    2
Name: USER_ID, dtype: int64
291
30    1
Name: USER_ID, dtype: int64
292
30    4
36    4
Name: USER_ID, dtype: int64
293
30    5
36    3
Name: USER_ID, dtype: int64
294
30    3
36    2
Name: USER_ID, dtype: int64
295
35    4
30    1
40    1
Name: USER_ID, dtype: int64
296
30    25
40     8
Name: USER_ID, dtype: int64
297
36    2
30    1
Name: USER_ID, dtype: int64
298
31    1
30    1
36    1
Name: USER_ID, dtype: int64
299
30    1
Name: USER_ID, dtype: int64
300
36    4
30    1
57    1
Name: USER_ID, dtype: int64
301
30    1
Name: USER_ID, dtype: int64
302
30    1
Name: USER_ID, dtype: int64
303
30    1
Name: USER_ID, dtype: int64
304
30    1
Name: USER_ID, dtype: int64
305
35    3
30    1
Name: USER_ID, dtype: int64
306
31    2
Name: USER_ID, dtype: int64
307
32    93
42    58
50    57
60     6
63     4
Name: USER_ID, dtype: int64
308
32    4
47    1
Name: USER_ID, dtype: int64
309
32    1
Name: USER_ID, dtype: int64
310
32    4
42    2
Name: USER_ID, dtype: int64
311
38    6
32    1
Name: USER_ID, dtype: int64
312
47    1
32    1
Name: USER_ID, dtype: int64
313
32    1
Name: USER_ID, dtype: int64
314
32    2
Name: USER_ID, dtype: int64
315
40    4
33    2
60    1
Name: USER_ID, dtype: int64
316
44    4
55    4
33    1
Name: USER_ID, dtype: int64
317
44    4
55    4
33    1
Name: USER_ID, dtype: int64
318
55    3
44    2
33    1
Name: USER_ID, dtype: int64
319
34    1
Name: USER_ID, dtype: int64
320
34    1
Name: USER_ID, dtype: int64
321
35    8
44    4
61    2
Name: USER_ID, dtype: int64
322
35    2
Name: USER_ID, dtype: int64
323
35    1
Name: USER_ID, dtype: int64
324
38    2
36    2
35    1
Name: USER_ID, dtype: int64
325
35    1
Name: USER_ID, dtype: int64
326
36    1
Name: USER_ID, dtype: int64
327
36    2
Name: USER_ID, dtype: int64
328
36    6
49    1
Name: USER_ID, dtype: int64
329
36    5
57    2
46    1
Name: USER_ID, dtype: int64
330
36    2
Name: USER_ID, dtype: int64
331
36    2
Name: USER_ID, dtype: int64
332
36    1
Name: USER_ID, dtype: int64
333
53    2
36    1
Name: USER_ID, dtype: int64
334
36    2
53    1
Name: USER_ID, dtype: int64
335
36    1
Name: USER_ID, dtype: int64
336
36    1
Name: USER_ID, dtype: int64
337
36    5
Name: USER_ID, dtype: int64
338
36    1
Name: USER_ID, dtype: int64
339
38    2
Name: USER_ID, dtype: int64
340
38    1
Name: USER_ID, dtype: int64
341
42    1
38    1
Name: USER_ID, dtype: int64
342
42    1
38    1
Name: USER_ID, dtype: int64
343
38    1
Name: USER_ID, dtype: int64
344
38    1
Name: USER_ID, dtype: int64
345
40    2
Name: USER_ID, dtype: int64
346
40    1
Name: USER_ID, dtype: int64
347
40    1
Name: USER_ID, dtype: int64
348
41    4
56    3
Name: USER_ID, dtype: int64
349
41    1
Name: USER_ID, dtype: int64
350
41    2
44    1
Name: USER_ID, dtype: int64
351
41    2
Name: USER_ID, dtype: int64
352
42    10
Name: USER_ID, dtype: int64
353
42    1
Name: USER_ID, dtype: int64
354
42    1
Name: USER_ID, dtype: int64
355
50    7
42    1
Name: USER_ID, dtype: int64
356
42    1
Name: USER_ID, dtype: int64
357
43    1
45    1
Name: USER_ID, dtype: int64
358
43    1
Name: USER_ID, dtype: int64
359
44    1
Name: USER_ID, dtype: int64
360
44    4
47    1
61    1
Name: USER_ID, dtype: int64
361
44    1
Name: USER_ID, dtype: int64
362
44    1
Name: USER_ID, dtype: int64
363
44    2
58    1
61    1
Name: USER_ID, dtype: int64
364
45    1
Name: USER_ID, dtype: int64
365
45    1
Name: USER_ID, dtype: int64
366
47    3
53    1
Name: USER_ID, dtype: int64
367
47    3
Name: USER_ID, dtype: int64
368
47    1

Name: USER_ID, dtype: int64
369
47    1
Name: USER_ID, dtype: int64
370
49    1
Name: USER_ID, dtype: int64
371
49    1
Name: USER_ID, dtype: int64
372
49    1
Name: USER_ID, dtype: int64
373
50    3
Name: USER_ID, dtype: int64
374
50    2
Name: USER_ID, dtype: int64
375
51    2
Name: USER_ID, dtype: int64
376
51    2
Name: USER_ID, dtype: int64
377
51    1
Name: USER_ID, dtype: int64
378
51    1
Name: USER_ID, dtype: int64
379
51    1
Name: USER_ID, dtype: int64
380
52    1
Name: USER_ID, dtype: int64
381
53    2
Name: USER_ID, dtype: int64
382
53    1
Name: USER_ID, dtype: int64
383
53    1
Name: USER_ID, dtype: int64
384
53    2
Name: USER_ID, dtype: int64
385
53    1
61    1
Name: USER_ID, dtype: int64
386
53    1
61    1
Name: USER_ID, dtype: int64
387
53    1
Name: USER_ID, dtype: int64
388
53    1
Name: USER_ID, dtype: int64
389
53    1
Name: USER_ID, dtype: int64
390
55    1
Name: USER_ID, dtype: int64
391
55    1
Name: USER_ID, dtype: int64
392
55    1
Name: USER_ID, dtype: int64
393
56    2
Name: USER_ID, dtype: int64
394
56    2
Name: USER_ID, dtype: int64
395
56    1
Name: USER_ID, dtype: int64
396
56    1
Name: USER_ID, dtype: int64
397
56    2
Name: USER_ID, dtype: int64
398
56    2
Name: USER_ID, dtype: int64
399
57    1
Name: USER_ID, dtype: int64
400
57    1
Name: USER_ID, dtype: int64
401
57    1
Name: USER_ID, dtype: int64
402
57    1
Name: USER_ID, dtype: int64
403
57    1
Name: USER_ID, dtype: int64
404
57    1
Name: USER_ID, dtype: int64
405
57    1
Name: USER_ID, dtype: int64
406
57    1
Name: USER_ID, dtype: int64
407
58    1
Name: USER_ID, dtype: int64
408
59    1
Name: USER_ID, dtype: int64
409
59    2
Name: USER_ID, dtype: int64
410
59    1
Name: USER_ID, dtype: int64
411
59    1
Name: USER_ID, dtype: int64
412
59    1
Name: USER_ID, dtype: int64
413
59    1
Name: USER_ID, dtype: int64
414
60    1
Name: USER_ID, dtype: int64

In [50]:
data = pd.DataFrame()
for name,group in user:
    if data.empty:
        data = group.set_index("USER_ID")
data.head()

                  FEC_EVENT  PAGE  mes
USER_ID
0       2018-03-30 07:35:48     1    3
0       2018-02-18 13:26:45     1    2
0       2018-03-04 18:04:12     1    3
0       2018-01-04 08:29:59     1    1
0       2018-01-04 08:52:16     1    1

In [64]:
user.get_group(1)['USER_ID'].value_counts().index

Int64Index([24, 22, 50,  0, 58, 12,  1, 32, 13, 15, 44,  7, 29, 62, 42, 49, 48,
            28, 10,  4, 11, 61, 55,  2, 51, 56, 53, 63, 31, 14, 52, 40, 30, 57,
            34, 26,  9, 60, 16, 36, 38, 41, 54],
           dtype='int64')

In [73]:
index = df_test['USER_ID'].unique()

In [74]:
y['USER_ID'].value_counts())

In [106]:
data = {}
for x,y in user:
    data[x] = y['USER_ID'].value_counts()

In [108]:
asd = pd.DataFrame(data)

In [109]:
asd

,1,2,3,4,5,6,7,8,9,10,...,405,406,407,408,409,410,411,412,413,414
0,107.0,125,44.0,15.0,2.0,12.0,1.0,1.0,78.0,327.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,78.0,75,17.0,9.0,1.0,1.0,NaN,NaN,29.0,110.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16.0,66,32.0,9.0,9.0,NaN,NaN,NaN,19.0,61.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,40,8.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,25.0,123,94.0,NaN,24.0,27.0,NaN,1.0,3.0,347.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,133,32.0,3.0,4.0,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,13,13.0,3.0,2.0,NaN,NaN,NaN,3.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,39.0,40,6.0,1.0,NaN,NaN,NaN,1.0,51.0,170.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,48,10.0,3.0,2.0,NaN,NaN,NaN,20.0,79.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2.0,49,46.0,13.0,5.0,NaN,NaN,NaN,4.0,96.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,25.0,2,1.0,NaN,NaN,NaN,NaN,NaN,1.0,37.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,21.0,49,2.0,1.0,NaN,NaN,NaN,NaN,28.0,66.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,84.0,104,19.0,7.0,5.0,1.0,NaN,NaN,51.0,157.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,50.0,43,4.0,NaN,NaN,NaN,NaN,NaN,9.0,143.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,7.0,14,3.0,NaN,1.0,NaN,NaN,NaN,2.0,56.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,49.0,78,34.0,9.0,1.0,NaN,NaN,NaN,NaN,56.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1.0,48,46.0,8.0,5.0,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,60,28.0,5.0,11.0,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,5,2.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,33,7.0,4.0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,102,85.0,20.0,9.0,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,18,24.0,3.0,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,180.0,125,7.0,3.0,3.0,NaN,NaN,NaN,66.0,439.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,42,2.0,1.0,NaN,NaN,NaN,NaN,NaN,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,424.0,289,21.0,1.0,NaN,2.0,NaN,NaN,142.0,816.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,38,34.0,6.0,10.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2.0,90,2.0,2.0,NaN,NaN,NaN,NaN,53.0,239.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,50,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29.0,31,NaN,NaN,NaN,NaN,NaN,NaN,21.0,71.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,36.0,19,NaN,NaN,NaN,NaN,NaN,NaN,19.0,66.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34,3.0,29,52.0,16.0,6.0,2.0,NaN,NaN,10.0,181.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,193,41.0,13.0,4.0,16.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,1.0,129,134.0,16.0,7.0,34.0,1.0,1.0,88.0,786.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,85,7.0,1.0,NaN,NaN,NaN,NaN,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,1.0,108,88.0,1.0,10.0,NaN,NaN,1.0,83.0,238.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,11,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,5.0,74,70.0,8.0,19.0,1.0,NaN,NaN,14.0,44.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,1.0,87,2.0,1.0,NaN,NaN,NaN,NaN,2.0,308.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,34.0,71,13.0,8.0,NaN,1.0,NaN,NaN,57.0,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,35,43.0,3.0,8.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,41.0,76,32.0,10.0,1.0,NaN,NaN,NaN,6.0,249.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,46,53.0,10.0,21.0,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,47,28.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,179,15.0,15.0,4.0,NaN,NaN,NaN,75.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,31.0,22,11.0,2.0,NaN,3.0,NaN,NaN,6.0,63.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,34.0,59,17.0,10.0,1.0,NaN,NaN,NaN,30.0,94.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,138.0,145,40.0,2.0,6.0,4.0,NaN,NaN,72.0,316.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,15.0,45,18.0,1.0,NaN,NaN,NaN,NaN,1.0,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,6.0,10,NaN,NaN,NaN,NaN,NaN,NaN,10.0,22.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,11.0,69,9.0,4.0,7.0,NaN,NaN,NaN,1090.0,336.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,1.0,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,16.0,30,57.0,6.0,9.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,15.0,66,11.0,NaN,2.0,NaN,NaN,NaN,30.0,228.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,3.0,58,29.0,6.0,NaN,1.0,NaN,NaN,6.0,15.0,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,86.0,96,4.0,NaN,NaN,NaN,NaN,NaN,55.0,403.0,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,NaN,15,24.0,10.0,2.0,NaN,NaN,NaN,6.0,19.0,...,NaN,NaN,NaN,1.0,2.0,1.0,1.0,1.0,1.0,NaN
60,2.0,67,50.0,7.0,8.0,5.0,NaN,NaN,19.0,199.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
61,18.0,143,35.0,4.0,11.0,2.0,NaN,NaN,20.0,296.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,36.0,101,93.0,12.0,39.0,NaN,NaN,NaN,20.0,44.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,10.0,4,NaN,NaN,NaN,NaN,NaN,NaN,1.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN